Lection6 hw
VyacheslavReetz/Git_hw pull request #7
Opened 2024-06-04 06:32 UTC by VyacheslavReetz

3 Tasks for ObjectsHW

2024-06-04 07:19 UTC, VladimirLQA approved these changes

2024-06-04 07:19 UTC, VladimirLQA commented on lection6/task2.js
> +function isMyNumbersUnique(myNumbers) {
No need to use sort for this task, it's excess action
Try to use two arrays and loop with `indexOf` check, for example
```
const uniqueNumbers = [];
const seenNumbers = [];
```

2024-06-04 07:19 UTC, VladimirLQA commented on lection6/task2.js
> +    let result = myNumbers;
Add validation for cases if passed value is not an array or it can be empty and if it empty we should retun a `null`

2024-06-04 07:19 UTC, VladimirLQA commented on lection6/task2.js
> +  }
```suggestion
function palindrome(str) {
    return str.toLowerCase() === str.toLowerCase().split('').reverse().join('') 
          ? `Палиндром` : 'Не палиндром';
  }
```

2024-06-04 12:53 UTC, anatoly-karpovich requested changes

2024-06-04 12:53 UTC, anatoly-karpovich commented on lection6/task3.js
> +function recursion(number) {
change function name to task-related one like getSumOfDigits

2024-06-04 12:53 UTC, anatoly-karpovich commented on lection6/task3.js
> +function transformer(string) {  // работает и с верхним регистром
try this 
console.log(transformer("baac")); 

should return baac => bbc => cc => d

2024-06-05 10:54 UTC, VyacheslavReetz commented on lection6/task2.js
> +  }
prettily

2024-06-05 16:37 UTC, VladimirLQA approved these changes

2024-06-05 16:37 UTC, VladimirLQA commented on lection5/task3.js
>  for (let char of str) {
```suggestion
for (let char of str.toLowerCase()) {
```
Convert test word to lower case

2024-06-05 16:37 UTC, VladimirLQA commented on lection5/task3.js
>      if(vowelsStr.indexOf(char) > -1 || vowelsStr.toUpperCase().indexOf(char) > -1) {
And here just 
```suggestion
    if(vowelsStr.includes(char)) {
```
Same for the consonants

2024-06-05 16:37 UTC, VladimirLQA commented on lection6/task1.js
> +function getEmployeeInfo(name) {
Add validation for passed argument

2024-06-05 16:37 UTC, VladimirLQA commented on lection6/task2.js
> +function isMyPizzaUnique(myPizzas) {
Add validation for passed argument
Good practice is to convert pizza names to lower case and compare them

2024-06-05 16:37 UTC, VladimirLQA commented on lection6/task2.js
> +    return result;
```suggestion
    return wordArray.join(', ');
```

2024-06-07 19:23 UTC, VladimirLQA approved these changes

2024-06-16 10:37 UTC, merged